USE [master];
GO
CREATE LOGIN Deepak WITH PASSWORD = 'Deepak#1', CHECK_POLICY = OFF
GO
CREATE DATABASE CONCENTO
GO
ALTER AUTHORIZATION ON DATABASE:: CONCENTO TO Deepak;
GO
CREATE DATABASE DEPLOY2
GO
ALTER AUTHORIZATION ON DATABASE:: DEPLOY2 TO Deepak;
GO
CREATE DATABASE ENRICH
GO
ALTER AUTHORIZATION ON DATABASE:: ENRICH TO Deepak;
GO
CREATE DATABASE REPORT
GO
ALTER AUTHORIZATION ON DATABASE:: REPORT TO Deepak;
GO
CREATE DATABASE FOO
GO
ALTER AUTHORIZATION ON DATABASE:: FOO TO Deepak;
GO
CREATE DATABASE srcFOO
GO
ALTER AUTHORIZATION ON DATABASE:: srcFOO TO Deepak;
GO
CREATE DATABASE BAR
GO
ALTER AUTHORIZATION ON DATABASE:: BAR TO Deepak;
GO
CREATE DATABASE tgtBAR
GO
ALTER AUTHORIZATION ON DATABASE:: tgtBAR TO Deepak;
GO
CREATE DATABASE wrkFOO2BAR
GO
ALTER AUTHORIZATION ON DATABASE:: wrkFOO2BAR TO Deepak;
GO

